variable "region"         {default ="" }
variable "vpc_name"       {default = "" }
variable "range"          { }
variable "environment"            {default = " " }
variable "environment-purpose"  {default = " " }
variable "category"     {default = " " }
variable "client"          {default = " " }
variable "costcode"      {default = " " }
variable "vpc_id"          {default = " " }
variable "port_55_60"      {default = " " }
variable "all_tcp_udp"  {default = " " }
variable "port_443"    {default = " " }
variable "port_89"    {default = " " }
variable "port_97"    {default = " " }
variable "rdp_ssh"    {default = " " }
variable "jb"        {default = " " }
variable "rapid_scan_console"    {default = " " }
variable "rapid"    {default = " " }
variable "ansible"         {default = " " }
variable "ansibledev"         {default = " " }
variable "corp"         {default = " " }
variable "public"         {default = " " }
variable "tf_state_bucket"    {default = " " }
variable "resource-tag"         {default = " " }